/**
 * NPL Hub Nepal — SQL Seed Generator
 *
 * Reads canonical TypeScript data models and compiles a deterministic,
 * idempotent PostgreSQL seed script at `supabase/seed.sql`.
 *
 * Run: npx tsx scripts/generate-seed-sql.ts
 * Add to package.json: "seed:generate": "npx tsx scripts/generate-seed-sql.ts"
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { SEASON_2_STATS_DATASET } from '../src/lib/data/stats-season2-data';
import { SEASON_3_STATS_DATASET } from '../src/lib/data/stats-season3-data';
import { NPL_TEAM_DETAILS } from '../src/lib/data/teams-data';
import { NPL_PLAYERS } from '../src/lib/data/players-data';
import { SCHEDULE_FIXTURES } from '../src/lib/data/schedule-data';
import { NEWS_ARTICLES } from '../src/lib/data/news-data';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outputPath = path.resolve(__dirname, '../supabase/seed.sql');

// ---------------------------------------------------------------------------
// SQL escaping helpers
// ---------------------------------------------------------------------------
function esc(val: unknown): string {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return isNaN(val as number) ? 'NULL' : String(val);
  if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
  if (Array.isArray(val)) {
    if (val.length === 0) return "'{}'";
    const items = val.map((v) => `"${String(v).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`);
    return `'{${items.join(',')}}'`;
  }
  if (typeof val === 'object') {
    return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
  }
  // string
  return `'${String(val).replace(/'/g, "''")}'`;
}

let sql = `-- ==============================================================================
-- NPL Hub Nepal — Canonical Data Seed Script
-- Generated by: scripts/generate-seed-sql.ts
-- Deterministic & Idempotent (ON CONFLICT DO UPDATE / DO NOTHING)
-- ==============================================================================

BEGIN;

`;

const lines: string[] = [];

// ============================================================================
// 1. SEASONS
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 1. SEASONS (2 Records)`);
lines.push(`-- ------------------------------------------------------------------------------`);

const s2 = SEASON_2_STATS_DATASET.summary;
const s3 = SEASON_3_STATS_DATASET.summary;

const seasonsRows = [
  {
    id: 'season-2',
    name: s2.name,
    short_name: s2.shortName,
    year: 2025,
    status: 'completed',
    edition: s2.edition,
    dates_display: s2.dates,
    start_date: s2.startDate,
    end_date: s2.endDate,
    venue: s2.venue,
    venue_city: s2.venueCity,
    total_teams: s2.teamsCount,
    total_matches: s2.totalMatches,
    league_matches: s2.leagueMatches,
    playoff_matches: s2.playoffMatches,
    format: s2.format,
    points_system: s2.pointsSystem,
    confidence: s2.confidence,
    confidence_note: s2.confidenceNote ?? null,
  },
  {
    id: 'season-3',
    name: s3.name,
    short_name: s3.shortName,
    year: 2026,
    status: 'pre-tournament',
    edition: s3.edition,
    dates_display: s3.dates,
    start_date: s3.startDate,
    end_date: s3.endDate,
    venue: s3.venue,
    venue_city: s3.venueCity,
    total_teams: s3.teamsCount,
    total_matches: s3.totalMatches,
    league_matches: s3.leagueMatches,
    playoff_matches: s3.playoffMatches,
    format: s3.format,
    points_system: s3.pointsSystem,
    confidence: s3.confidence,
    confidence_note: s3.confidenceNote ?? null,
  },
];

for (const r of seasonsRows) {
  lines.push(`INSERT INTO public.seasons (
  id, name, short_name, year, status, edition, dates_display, start_date, end_date,
  venue, venue_city, total_teams, total_matches, league_matches, playoff_matches,
  format, points_system, confidence, confidence_note
) VALUES (
  ${esc(r.id)}, ${esc(r.name)}, ${esc(r.short_name)}, ${esc(r.year)}, ${esc(r.status)},
  ${esc(r.edition)}, ${esc(r.dates_display)}, ${esc(r.start_date)}, ${esc(r.end_date)},
  ${esc(r.venue)}, ${esc(r.venue_city)}, ${esc(r.total_teams)}, ${esc(r.total_matches)},
  ${esc(r.league_matches)}, ${esc(r.playoff_matches)}, ${esc(r.format)},
  ${esc(r.points_system)}, ${esc(r.confidence)}, ${esc(r.confidence_note)}
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, short_name = EXCLUDED.short_name, year = EXCLUDED.year,
  status = EXCLUDED.status, edition = EXCLUDED.edition, dates_display = EXCLUDED.dates_display,
  start_date = EXCLUDED.start_date, end_date = EXCLUDED.end_date, venue = EXCLUDED.venue,
  venue_city = EXCLUDED.venue_city, format = EXCLUDED.format, points_system = EXCLUDED.points_system,
  confidence = EXCLUDED.confidence, confidence_note = EXCLUDED.confidence_note,
  updated_at = timezone('utc'::text, now());`);
}
lines.push('');

// ============================================================================
// 2. TEAMS
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 2. TEAMS (8 Franchise Teams)`);
lines.push(`-- ------------------------------------------------------------------------------`);

for (const t of NPL_TEAM_DETAILS) {
  lines.push(`INSERT INTO public.teams (
  id, slug, name, short_name, initials, region, city,
  brand_color, brand_bg, crest_bg, crest_text, logo_url, established, description
) VALUES (
  ${esc(t.id)}, ${esc(t.slug)}, ${esc(t.name)}, ${esc(t.shortName)}, ${esc(t.initials)},
  ${esc(t.region)}, ${esc(t.city)}, ${esc(t.brandColor)}, ${esc(t.brandBg)},
  ${esc(t.crestBg)}, ${esc(t.crestText)}, ${esc(t.logoUrl ?? null)},
  ${esc(t.established)}, ${esc(t.description)}
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, short_name = EXCLUDED.short_name, initials = EXCLUDED.initials,
  region = EXCLUDED.region, city = EXCLUDED.city, brand_color = EXCLUDED.brand_color,
  brand_bg = EXCLUDED.brand_bg, crest_bg = EXCLUDED.crest_bg, crest_text = EXCLUDED.crest_text,
  logo_url = EXCLUDED.logo_url, established = EXCLUDED.established, description = EXCLUDED.description,
  updated_at = timezone('utc'::text, now());`);
}

// After teams, attach Season 2 champion/runner-up references
lines.push('');
lines.push(`-- Attach Season 2 champion and runner-up FK references`);
lines.push(`UPDATE public.seasons SET champion_team_id = ${esc(s2.champion?.teamId ?? null)}, runner_up_team_id = ${esc(s2.runnerUp?.teamId ?? null)} WHERE id = 'season-2';`);
lines.push('');

// ============================================================================
// 3. TEAM_SEASONS
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 3. TEAM_SEASONS`);
lines.push(`-- 3a. Season 2 — Authoritative final standings (8 teams)`);
lines.push(`-- ------------------------------------------------------------------------------`);

for (const row of SEASON_2_STATS_DATASET.standings) {
  const tsId = `season-2_${row.teamId}`;
  lines.push(`INSERT INTO public.team_seasons (
  id, season_id, team_id, standing_position, played, won, lost, no_result, points, net_run_rate
) VALUES (
  ${esc(tsId)}, 'season-2', ${esc(row.teamId)}, ${esc(row.position)},
  ${esc(row.played)}, ${esc(row.won)}, ${esc(row.lost)}, ${esc(row.noResult)},
  ${esc(row.points)}, ${esc(row.netRunRate)}
) ON CONFLICT (season_id, team_id) DO UPDATE SET
  standing_position = EXCLUDED.standing_position, played = EXCLUDED.played,
  won = EXCLUDED.won, lost = EXCLUDED.lost, no_result = EXCLUDED.no_result,
  points = EXCLUDED.points, net_run_rate = EXCLUDED.net_run_rate,
  updated_at = timezone('utc'::text, now());`);
}

lines.push('');
lines.push(`-- 3b. Season 3 — Pre-tournament: roster metadata only, no standings yet`);
for (const t of NPL_TEAM_DETAILS) {
  const tsId = `season-3_${t.id}`;
  lines.push(`INSERT INTO public.team_seasons (
  id, season_id, team_id, captain_name, captain_confidence, captain_source,
  captain_confirmed_at, coach, squad_status, played, won, lost, no_result, points
) VALUES (
  ${esc(tsId)}, 'season-3', ${esc(t.id)}, ${esc(t.captain)}, ${esc(t.captainConfidence)},
  ${esc(t.captainSource)}, ${esc(t.captainConfirmedAt)}, ${esc(t.coach)}, ${esc(t.squadStatus)},
  0, 0, 0, 0, 0
) ON CONFLICT (season_id, team_id) DO UPDATE SET
  captain_name = EXCLUDED.captain_name, captain_confidence = EXCLUDED.captain_confidence,
  captain_source = EXCLUDED.captain_source, captain_confirmed_at = EXCLUDED.captain_confirmed_at,
  coach = EXCLUDED.coach, squad_status = EXCLUDED.squad_status,
  updated_at = timezone('utc'::text, now());`);
}
lines.push('');

// ============================================================================
// 4. PLAYERS
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 4. PLAYERS (${NPL_PLAYERS.length} Canonical Season 3 Retained Players)`);
lines.push(`-- ------------------------------------------------------------------------------`);

for (const p of NPL_PLAYERS) {
  lines.push(`INSERT INTO public.players (
  id, slug, name, display_name, nationality, date_of_birth, birth_place,
  batting_style, bowling_style, profile_image, bio
) VALUES (
  ${esc(p.id)}, ${esc(p.slug)}, ${esc(p.name)}, ${esc(p.displayName ?? null)},
  ${esc(p.nationality)}, ${esc(p.dateOfBirth ?? null)}, ${esc(p.birthPlace ?? null)},
  ${esc(p.battingStyle ?? null)}, ${esc(p.bowlingStyle ?? null)},
  ${esc(p.profileImage ?? null)}, ${esc(p.bio ?? null)}
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, display_name = EXCLUDED.display_name, nationality = EXCLUDED.nationality,
  date_of_birth = EXCLUDED.date_of_birth, birth_place = EXCLUDED.birth_place,
  batting_style = EXCLUDED.batting_style, bowling_style = EXCLUDED.bowling_style,
  profile_image = EXCLUDED.profile_image, bio = EXCLUDED.bio,
  updated_at = timezone('utc'::text, now());`);
}
lines.push('');

// ============================================================================
// 5. PLAYER_SEASONS
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 5. PLAYER_SEASONS (${NPL_PLAYERS.length} Season 3 Player-Team Relations)`);
lines.push(`-- ------------------------------------------------------------------------------`);

for (const p of NPL_PLAYERS) {
  const psId = `season-3_${p.id}`;
  lines.push(`INSERT INTO public.player_seasons (
  id, season_id, player_id, team_id, role, status, captain, marquee,
  player_number, confidence, source, source_url, source_date
) VALUES (
  ${esc(psId)}, 'season-3', ${esc(p.id)}, ${esc(p.teamId)}, ${esc(p.role)},
  ${esc(p.status)}, ${esc(p.captain)}, ${esc(p.marquee ?? false)}, ${esc(p.playerNumber ?? null)},
  ${esc(p.confidence)}, ${esc(p.source)}, ${esc(p.sourceUrl ?? null)}, ${esc(p.sourceDate ?? null)}
) ON CONFLICT (season_id, player_id) DO UPDATE SET
  team_id = EXCLUDED.team_id, role = EXCLUDED.role, status = EXCLUDED.status,
  captain = EXCLUDED.captain, marquee = EXCLUDED.marquee, player_number = EXCLUDED.player_number,
  confidence = EXCLUDED.confidence, source = EXCLUDED.source,
  source_url = EXCLUDED.source_url, source_date = EXCLUDED.source_date,
  updated_at = timezone('utc'::text, now());`);
}
lines.push('');

// ============================================================================
// 6. MATCHES
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 6. MATCHES (${SCHEDULE_FIXTURES.length} Season 3 Fixtures, 28 League + 4 Playoff)`);
lines.push(`-- Playoff matches 29-32 use nullable team IDs + exclusive placeholder values.`);
lines.push(`-- ------------------------------------------------------------------------------`);

for (const m of SCHEDULE_FIXTURES) {
  lines.push(`INSERT INTO public.matches (
  id, season_id, match_number, slug, stage,
  team1_id, team1_placeholder, team2_id, team2_placeholder,
  match_date, formatted_date, bs_date, bs_date_nepali, day_of_week,
  match_time, venue, status, is_provisional
) VALUES (
  ${esc(m.id)}, 'season-3', ${esc(m.matchNumber)}, ${esc(m.slug)}, ${esc(m.stage)},
  ${esc(m.team1Id)}, ${esc(m.team1Placeholder)}, ${esc(m.team2Id)}, ${esc(m.team2Placeholder)},
  ${esc(m.date)}, ${esc(m.formattedDate)}, ${esc(m.bsDate)}, ${esc(m.bsDateNepali)},
  ${esc(m.dayOfWeek)}, ${esc(m.time)}, ${esc(m.venue)}, ${esc(m.status)}, ${esc(m.isProvisional)}
) ON CONFLICT (season_id, match_number) DO UPDATE SET
  slug = EXCLUDED.slug, stage = EXCLUDED.stage,
  team1_id = EXCLUDED.team1_id, team1_placeholder = EXCLUDED.team1_placeholder,
  team2_id = EXCLUDED.team2_id, team2_placeholder = EXCLUDED.team2_placeholder,
  match_date = EXCLUDED.match_date, formatted_date = EXCLUDED.formatted_date,
  bs_date = EXCLUDED.bs_date, bs_date_nepali = EXCLUDED.bs_date_nepali,
  day_of_week = EXCLUDED.day_of_week, match_time = EXCLUDED.match_time,
  venue = EXCLUDED.venue, status = EXCLUDED.status, is_provisional = EXCLUDED.is_provisional,
  updated_at = timezone('utc'::text, now());`);
}
lines.push('');

// ============================================================================
// 7. NEWS_ARTICLES
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 7. NEWS_ARTICLES (${NEWS_ARTICLES.length} Articles)`);
lines.push(`-- ------------------------------------------------------------------------------`);

// The NewsArticle schema in the DB has: author_role, read_time, tags, source_url
// The TypeScript model has: author (no authorRole), readTime, source (string, not url), no tags
// Map accordingly:
for (const a of NEWS_ARTICLES) {
  const contentJson = JSON.stringify(a.content);
  lines.push(`INSERT INTO public.news_articles (
  id, slug, title, excerpt, content, category, status, featured,
  image_url, author, author_role, read_time, tags, source, source_url,
  published_at, updated_at
) VALUES (
  ${esc(a.id)}, ${esc(a.slug)}, ${esc(a.title)}, ${esc(a.excerpt)},
  '${contentJson.replace(/'/g, "''")}'::jsonb,
  ${esc(a.category)}, ${esc(a.status)}, ${esc(a.featured)},
  ${esc(a.imageUrl ?? null)}, ${esc(a.author)},
  'Editorial', ${esc(a.readTime)}, '{}', ${esc(a.source ?? null)}, NULL,
  ${esc(a.publishedAt)}, ${esc(a.updatedAt)}
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, title = EXCLUDED.title, excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content, category = EXCLUDED.category, status = EXCLUDED.status,
  featured = EXCLUDED.featured, image_url = EXCLUDED.image_url, author = EXCLUDED.author,
  read_time = EXCLUDED.read_time, source = EXCLUDED.source,
  published_at = EXCLUDED.published_at, updated_at = EXCLUDED.updated_at;`);
}
lines.push('');

// ============================================================================
// 8. NEWS_TEAM_RELATIONS
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 8. NEWS_TEAM_RELATIONS`);
lines.push(`-- ------------------------------------------------------------------------------`);

let relationCount = 0;
for (const a of NEWS_ARTICLES) {
  const teamIds = a.relatedTeamIds ?? [];
  for (const teamId of teamIds) {
    lines.push(`INSERT INTO public.news_team_relations (article_id, team_id)
VALUES (${esc(a.id)}, ${esc(teamId)})
ON CONFLICT (article_id, team_id) DO NOTHING;`);
    relationCount++;
  }
}
if (relationCount === 0) {
  lines.push(`-- No team relations in current news articles (relatedTeamIds are empty)`);
}
lines.push('');

// ============================================================================
// 9. PLAYER_SEASON_STATS (Season 2 verified records only)
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 9. PLAYER_SEASON_STATS — Season 2 verified (${SEASON_2_STATS_DATASET.playerStats.length} players)`);
lines.push(`-- NULL values are preserved as-is; NOT replaced with 0.`);
lines.push(`-- Season 3: no stats seeded (pre-tournament, no data exists).`);
lines.push(`-- ------------------------------------------------------------------------------`);

for (const stat of SEASON_2_STATS_DATASET.playerStats) {
  const statId = `s2_${stat.id}`;
  const highestScoreStr = stat.highestScore !== null && stat.highestScore !== undefined
    ? String(stat.highestScore)
    : null;

  lines.push(`INSERT INTO public.player_season_stats (
  id, season_id, player_name, player_slug, team_id, team_name,
  matches, innings, runs, highest_score, average, strike_rate,
  wickets, best_bowling, economy, fours, sixes, hundreds, fifties,
  catches, wicketkeeper_dismissals, confidence, source_note
) VALUES (
  ${esc(statId)}, 'season-2', ${esc(stat.playerName)}, ${esc(stat.playerSlug ?? null)},
  ${esc(stat.teamId)}, ${esc(stat.teamName)},
  ${esc(stat.matches)}, ${esc(stat.innings)}, ${esc(stat.runs)}, ${esc(highestScoreStr)},
  ${esc(stat.average)}, ${esc(stat.strikeRate)},
  ${esc(stat.wickets)}, ${esc(stat.bestBowling)}, ${esc(stat.economy)},
  ${esc(stat.fours)}, ${esc(stat.sixes)}, ${esc(stat.hundreds)}, ${esc(stat.fifties)},
  ${esc(stat.catches)}, ${esc(stat.wicketkeeperDismissals)},
  ${esc(stat.confidence)}, ${esc(stat.sourceNote ?? null)}
) ON CONFLICT (season_id, player_name, team_id) DO UPDATE SET
  player_slug = EXCLUDED.player_slug, team_name = EXCLUDED.team_name,
  matches = EXCLUDED.matches, innings = EXCLUDED.innings, runs = EXCLUDED.runs,
  highest_score = EXCLUDED.highest_score, average = EXCLUDED.average,
  strike_rate = EXCLUDED.strike_rate, wickets = EXCLUDED.wickets,
  best_bowling = EXCLUDED.best_bowling, economy = EXCLUDED.economy,
  fours = EXCLUDED.fours, sixes = EXCLUDED.sixes,
  hundreds = EXCLUDED.hundreds, fifties = EXCLUDED.fifties,
  catches = EXCLUDED.catches, wicketkeeper_dismissals = EXCLUDED.wicketkeeper_dismissals,
  confidence = EXCLUDED.confidence, source_note = EXCLUDED.source_note,
  updated_at = timezone('utc'::text, now());`);
}
lines.push('');

// ============================================================================
// 10. TOURNAMENT_AWARDS (Season 2 verified awards)
// ============================================================================
lines.push(`-- ------------------------------------------------------------------------------`);
lines.push(`-- 10. TOURNAMENT_AWARDS — Season 2 verified (${SEASON_2_STATS_DATASET.awards.length} awards)`);
lines.push(`-- Uses ON CONFLICT DO NOTHING to avoid overwriting; awards use UUID PKs.`);
lines.push(`-- ------------------------------------------------------------------------------`);

let sortOrder = 1;
for (const aw of SEASON_2_STATS_DATASET.awards) {
  lines.push(`INSERT INTO public.tournament_awards (
  season_id, award_type, award_name, recipient_name, recipient_player_slug,
  recipient_team_id, recipient_team_name, secondary_detail, confidence, source_note, sort_order
) VALUES (
  'season-2', ${esc(aw.id)}, ${esc(aw.title)}, ${esc(aw.recipient)}, ${esc(aw.playerSlug ?? null)},
  ${esc(aw.teamId)}, ${esc(aw.teamName)}, ${esc(aw.detail ?? null)},
  ${esc(aw.confidence)}, ${esc(aw.categoryNote ?? null)}, ${sortOrder++}
) ON CONFLICT DO NOTHING;`);
}
lines.push('');
lines.push(`COMMIT;`);
lines.push('');

sql += lines.join('\n');

fs.writeFileSync(outputPath, sql, 'utf8');
console.log(`✅ Seed SQL generated: ${outputPath}`);
console.log(`   Seasons:            2`);
console.log(`   Teams:              ${NPL_TEAM_DETAILS.length}`);
console.log(`   Team-Seasons:       ${NPL_TEAM_DETAILS.length * 2} (8 S2 standings + 8 S3 pre-tournament)`);
console.log(`   Players:            ${NPL_PLAYERS.length}`);
console.log(`   Player-Seasons:     ${NPL_PLAYERS.length}`);
console.log(`   Matches:            ${SCHEDULE_FIXTURES.length}`);
console.log(`   News Articles:      ${NEWS_ARTICLES.length}`);
console.log(`   News-Team Rels:     ${relationCount}`);
console.log(`   Player Stats (S2):  ${SEASON_2_STATS_DATASET.playerStats.length}`);
console.log(`   Tournament Awards:  ${SEASON_2_STATS_DATASET.awards.length}`);
console.log(`   File size:          ${sql.length} bytes`);
